export const phoneDisplay = '(214) 945-3694'
export const phoneHref = 'tel:+12149453694'
export const email = 'contact@coldshineauto.com'

export const reviews = [
  {
    text: "Made my headlights restored like they’re brand new! Highly recommend to anyone and everyone!",
    source: 'Verified Google Review',
  },
  {
    text: 'Awesome detail for a great price.',
    source: 'Verified Google Review',
  },
  {
    text: 'He got my 14 year old Lexus looking almost new again, and for a very fair price. I would 100% recommend him to anyone looking to get their vehicle detailed!',
    source: 'Verified Google Review',
  },
]

export const services = [
  {
    slug: 'full-detail',
    name: 'Full Detail',
    short: 'Deep interior reset + exterior wash for a complete transformation.',
    eyebrow: 'Inside + Out',
    image: 'hero-detailing.webp',
    intro: 'A complete reset for vehicles that need more than a quick wash. The Full Detail combines interior attention with a thorough exterior service so the entire vehicle leaves looking noticeably sharper.',
    includes: ['Interior vacuuming', 'Interior surface cleanup', 'Full body wash', 'Wheel washing', 'Exterior finishing touches'],
    ideal: ['Seasonal resets', 'Cars that have gone too long between details', 'Pre-sale cleanup', 'Daily drivers that need a full refresh'],
  },
  {
    slug: 'interior-detailing',
    name: 'Interior Detailing',
    short: 'Vacuuming and detail work focused on the cabin you use every day.',
    eyebrow: 'Cabin Reset',
    image: 'interior-detailing.webp',
    intro: 'Interior detailing focuses on the high-touch surfaces, carpets, seats, crevices and visual clutter that make a cabin feel worn. The goal is a cleaner, more comfortable interior without overlooking the small areas.',
    includes: ['Auto interior vacuuming', 'Carpet and floor-area attention', 'Seat and console cleanup', 'Dash and trim detailing', 'Crevice cleanup'],
    ideal: ['Daily commuters', 'Pet hair and everyday debris', 'Family vehicles', 'Cars that are clean outside but need cabin attention'],
  },
  {
    slug: 'exterior-detailing',
    name: 'Exterior Detailing',
    short: 'A focused exterior clean designed to restore a crisp, finished look.',
    eyebrow: 'Exterior Finish',
    image: 'mobile-detailing.webp',
    intro: 'Exterior detailing goes beyond simply rinsing the vehicle. The process focuses on the visible surfaces that determine how clean and well-kept the car actually looks.',
    includes: ['Full body wash', 'Wheel washing', 'Exterior glass', 'Trim wipe-down', 'Final finish inspection'],
    ideal: ['Routine upkeep', 'Road-film buildup', 'Weekend cars before an event', 'Drivers who want a clean finish without a full interior service'],
  },
  {
    slug: 'paint-correction',
    name: 'Paint Correction',
    short: 'Restore clarity, gloss and depth by reducing visible paint defects.',
    eyebrow: 'Gloss Restoration',
    image: 'hero-detailing.webp',
    intro: 'Paint correction is for customers who want the finish to look dramatically better, not simply cleaner. It is designed to improve gloss and reduce the appearance of swirls, haze and light defects.',
    includes: ['Paint-condition inspection', 'Surface preparation', 'Machine polishing', 'Gloss refinement', 'Final finish inspection'],
    ideal: ['Swirl-marked paint', 'Hazy or dull finishes', 'Enthusiast vehicles', 'Vehicles being prepared for ceramic protection'],
  },
  {
    slug: 'ceramic-coating',
    name: 'Ceramic Coating',
    short: 'Longer-term exterior protection with a slick, high-gloss finish.',
    eyebrow: 'Long-Term Protection',
    image: 'mobile-detailing.webp',
    intro: 'Ceramic coating is positioned for customers who want a stronger layer of protection and a finish that is easier to maintain. Proper preparation is key to getting the best result.',
    includes: ['Exterior preparation', 'Paint decontamination as needed', 'Surface refinement as needed', 'Ceramic coating application', 'Cure and finish inspection'],
    ideal: ['Newer vehicles', 'Freshly corrected paint', 'Customers who keep cars long term', 'Drivers who want easier maintenance and added gloss'],
  },
  {
    slug: 'headlight-restoration',
    name: 'Headlight Restoration',
    short: 'Bring cloudy or yellowed headlights back to a cleaner, clearer finish.',
    eyebrow: 'Clarity Restored',
    image: 'headlight-polishing.webp',
    intro: 'Cloudy headlights make an otherwise clean car look older. Headlight restoration focuses on improving clarity and appearance so the front end looks sharper again.',
    includes: ['Condition inspection', 'Surface preparation', 'Headlight polishing', 'Clarity refinement', 'Final wipe-down'],
    ideal: ['Yellowed lenses', 'Cloudy headlights', 'Older vehicles', 'Cars being cleaned up for sale'],
  },
  {
    slug: 'maintenance-detail',
    name: 'Maintenance Detail',
    short: 'Keep a recently detailed vehicle from sliding back into full-reset territory.',
    eyebrow: 'Stay Clean',
    image: 'interior-detailing.webp',
    intro: 'Maintenance detailing is for customers who would rather keep the vehicle consistently clean than wait until it needs another major reset.',
    includes: ['Light interior refresh', 'Routine exterior wash', 'Wheel cleanup', 'Glass and touch-point cleanup', 'Finish inspection'],
    ideal: ['Repeat customers', 'Garage-kept vehicles', 'Enthusiast cars', 'Busy owners who want a consistently clean vehicle'],
  },
  {
    slug: 'engine-detailing',
    name: 'Engine Detailing',
    short: 'A careful cleanup for one of the most overlooked areas of the vehicle.',
    eyebrow: 'Under-Hood Finish',
    image: 'mobile-detailing.webp',
    intro: 'Engine detailing is designed to improve the presentation of the engine bay with careful attention to visible dirt, dust and buildup.',
    includes: ['Engine-bay inspection', 'Controlled cleaning', 'Accessible surface wipe-down', 'Plastic and trim cleanup', 'Final presentation check'],
    ideal: ['Car-show preparation', 'Pre-sale presentation', 'Enthusiast vehicles', 'Owners who want the whole car cared for'],
  },
  {
    slug: 'car-waxing',
    name: 'Car Waxing',
    short: 'Add gloss and a fresh protective finish after the vehicle is properly cleaned.',
    eyebrow: 'Gloss + Protection',
    image: 'hero-detailing.webp',
    intro: 'Waxing gives a clean vehicle a richer finished look while adding a layer of surface protection. It works best when the paint has already been properly washed and prepared.',
    includes: ['Exterior wash preparation', 'Paint inspection', 'Wax application', 'Buff and finish', 'Final gloss inspection'],
    ideal: ['Routine protection', 'Older paint that needs added depth', 'Event preparation', 'Customers wanting a quick gloss upgrade'],
  },
  {
    slug: 'clay-bar-treatment',
    name: 'Clay Bar Treatment',
    short: 'Remove bonded contamination that normal washing leaves behind.',
    eyebrow: 'Paint Decontamination',
    image: 'mobile-detailing.webp',
    intro: 'A clay bar treatment targets contaminants that stay stuck to the paint after a normal wash. The result is a smoother surface that is better prepared for polishing, waxing or coating.',
    includes: ['Exterior wash', 'Surface inspection', 'Clay decontamination', 'Residue cleanup', 'Preparation for wax, polish or coating'],
    ideal: ['Rough-feeling paint', 'Vehicles with bonded road contamination', 'Pre-wax preparation', 'Pre-correction or coating preparation'],
  },
  {
    slug: 'wheel-washing',
    name: 'Wheel Washing',
    short: 'Focused cleaning for wheel faces and visible brake-dust buildup.',
    eyebrow: 'Wheel Care',
    image: 'mobile-detailing.webp',
    intro: 'Clean wheels change the appearance of the entire car. Wheel washing focuses on the areas where road grime and brake dust quickly make an otherwise clean vehicle look unfinished.',
    includes: ['Wheel-face cleaning', 'Visible brake-dust removal', 'Tire cleanup', 'Rinse and dry', 'Final visual inspection'],
    ideal: ['Brake-dust-heavy vehicles', 'Performance cars', 'Routine exterior maintenance', 'Customers who want the finish to look complete'],
  },
]

export const primaryServices = services.filter((service) => [
  'full-detail',
  'paint-correction',
  'ceramic-coating',
  'headlight-restoration',
  'maintenance-detail',
  'engine-detailing',
].includes(service.slug))
